### ISSUE TITLE
Can't compile siphashc on raspberry pi

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/siphashc#2]
Hi,

I can't figure out how to compile weblate for Raspberry Pi.
After solving swap issue, I now have things like:
```
as: error while loading shared libraries: /usr/lib/libbfd-2.25-system.so: ELF file version does not match current one
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

Here is the full log, which you'll find every commands used: https://pastebin.com/d1RbwWkG

The log is big, search `apt-get` and `pip install` helps to understand.

Have you ever tried this?

**Comment by nijel** [comment]
This really looks like a problem with your toolchain, though I have no clue to address this.

**Comment by Jibec** [comment]
I'm fine with closing this issue, I assume this is because of memory consumption. Thanks for your help and this tremendous work making a tool such as Weblate!

**Comment by nijel** [comment]
It might be problem with SD card as well, see https://github.com/XavierBerger/RPi-Monitor/issues/88 or https://www.raspberrypi.org/forums/viewtopic.php?t=170642
